name: cuidapet_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.3.0
  dotenv: ^4.1.0
  mysql1: ^0.20.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  get_it: ^7.6.0
  logger: ^1.4.0
  injectable: ^2.1.2
  jaguar_jwt: ^3.0.0
  http: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.6
  injectable_generator: ^2.1.6
  lints: ^2.1.1
  shelf_router_generator: ^1.0.6
  test: ^1.21.0
